name: Analytics a Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Actualizado a v4

    - name: Configurar Python
      uses: actions/setup-python@v5 # Actualizado a v5
      with:
        python-version: '3.12' # Usamos una versión de Python más reciente

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install google-analytics-data google-api-python-client google-auth

    - name: Ejecutar script
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python extract_data_ga4.py
